### ISSUE TITLE
issue with customized gallery 

### ISSUE THREAD

**Issue by LIU-FAYANG** [Martlgap/FaceIDLight#239]
Hi, when I was trying to run your demo with 
from FaceIDLight.demo import Demonstrator
Demonstrator(gal_dir=<full-path-to-your-gallery>).run()

this error would show up:
Python 3.8.18 (default, Sep 11 2023, 08:17:33) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from FaceIDLight.demo import Demonstrator
>>> Demonstrator(gal_dir='./proj1_gallary').run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/FaceIDLight/demo.py", line 38, in __init__
    self.FaceID = FaceID(gal_dir=gal_dir)
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/FaceIDLight/tools.py", line 62, in __init__
    self.update_gallery()
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/FaceIDLight/tools.py", line 81, in update_gallery
    self.gal_embs = self.recognizer.get_emb(np.asarray(self.gal_faces))[0]
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/FaceIDLight/tools.py", line 144, in get_emb
    return tflite_inference(self.face_recognizer, img)
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/FaceIDLight/tools.py", line 120, in tflite_inference
    model.allocate_tensors()
  File "/opt/anaconda3/envs/ee4208_proj1/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: external/org_tensorflow/tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 1)Node number 0 (PAD) failed to prepare.

Can I ask how to address this issue? I've checked the path to the galley folder is correct.

**Comment by LIU-FAYANG** [comment]
solved by crop images to suitable size
